version: "3"

services:
  app:
    build: .
    ports:
      - "5001:5001"
    command: "npm start"
    links:
    - db
  # working_dir: "/src"
  environment:
    SEQ_DB: blog
    SEQ_USER: postgres
    SEQ_PW: 0000
    PORT: 4242
    # DATABASE_URL: postgres://postgres:0000@127.0.0.1:5432/blog
  # volumes: ./:/src
    
db:
  image:
    postgres: 10.5-alpine
    environment:
    POSTGRES_USER: postgres         
    POSTGRES_PASSWORD: 0000         
    POSTGRES_DB: blog     
  ports:
    - 35432:543
  volumes:
    - /var/lib/postgresql/13/main    
